# Generated by Django 5.1.5 on 2025-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_childuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='afternoon_snack',
            field=models.TextField(blank=True, null=True, verbose_name='Полдник'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dinner',
            field=models.TextField(blank=True, null=True, verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='menu',
            name='second_breakfast',
            field=models.TextField(blank=True, null=True, verbose_name='Второй завтрак'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='breakfast',
            field=models.TextField(blank=True, null=True, verbose_name='Завтрак'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='lunch',
            field=models.TextField(blank=True, null=True, verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='snack',
            field=models.TextField(blank=True, null=True, verbose_name='Перекус'),
        ),
    ]
