# Generated by Django 5.1.5 on 2025-01-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_menu_options_menu_afternoon_snack_menu_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='snack',
        ),
    ]
