# Generated by Django 5.1.5 on 2025-01-21 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='childuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='childuser',
            name='password',
        ),
        migrations.AddField(
            model_name='childuser',
            name='parents',
            field=models.ManyToManyField(related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
