# Generated by Django 5.1.5 on 2025-01-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_gallerycategory_options_gallerymedia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymedia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallerymedia',
            name='title',
        ),
    ]
