# Generated by Django 5.1.5 on 2025-01-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_gallerymedia_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_full_name', models.CharField(max_length=100, verbose_name='Имя и Фамилия родителя')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('child_full_name', models.CharField(max_length=100, verbose_name='Имя и Фамилия ребенка')),
                ('child_birth_date', models.DateField()),
                ('message', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
